version: "3.9"

services:
  # Наш Python-застосунок (HTTP + Socket)
  app:
    build: .
    container_name: my_app
    # Пробросимо порти 3000 і 5000 назовні
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - my_network

  # Контейнер MongoDB
  mongo:
    image: mongo:6.0
    container_name: my_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
